#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { verifyRoot } = require('../verify/verify');

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) continue;
    const key = token.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith('--')) {
      args[key] = true;
    } else {
      args[key] = next;
      i += 1;
    }
  }
  return args;
}

function nextActionFor(failure) {
  const table = {
    missing_root_item: 'Run installer or restore the missing root file before planning.',
    missing_contract: 'Restore harness/contracts from the release package.',
    nested_harness_folder: 'Move harness files to the project root; do not keep a nested template clone.',
    secret_file_present: 'Do not read the value. Move/ignore the secret outside publishable harness scope.',
    harness_lock_missing_field: 'Regenerate harness.lock.yaml from installer receipt data.',
    planning_started_during_install: 'Treat install as contaminated; create a repair proposal and reset install-only state.',
    github_repo_created_during_install: 'Record as policy violation; future installer defaults must not create remote repos.',
    commit_created_during_install: 'Stop and ask for git cleanup instructions; do not rewrite history automatically.',
    push_performed_during_install: 'Stop and ask for remote cleanup instructions; do not mutate remote automatically.',
    active_task_single_default: 'Archive, cancel, or explicitly approve parallel active task handling.',
    projection_without_canonical_event: 'Regenerate projections from events.jsonl or ask the user for explicit approval again.',
    event_hash_chain_broken: 'Stop using this task state until the event log is audited; do not invent missing approvals.',
    event_required_fields: 'Repair event log only from trusted source events.',
    artifact_contract_parse_failed: 'Fix artifact-registry.yaml or skill-artifact-map.yaml; malformed routing contracts fail closed.',
    artifact_gate_unknown: 'Add the current gate to skill-artifact-map.yaml or correct task.yaml current_gate.',
    artifact_contract_unknown_artifact: 'Define the artifact in artifact-registry.yaml or remove the bad reference from skill-artifact-map.yaml.',
    artifact_read_receipt_missing: 'Read the required artifact, resolve its registry path, compute SHA-256 for file-backed artifacts, and append artifact_read with gate_id, artifact_id, path, hash, and proof_type.',
    artifact_forbidden_read: 'Stop the task and create a repair proposal; the current gate read a forbidden artifact.',
    artifact_required_write_missing: 'Create the required gate output artifact and append artifact_written with gate_id, artifact_id, repo-relative path, and file hash, or move the task back to the previous gate.',
    learning_capture_missing: 'Run lifecycle capture-learning before compound_capture finishes.',
    learning_capture_stale_template: 'Regenerate learning-capture.md from structured evidence; the starter template is not a valid capture result.',
    learning_capture_no_candidate_reason_missing: 'Add a no_candidate_reason with source hashes when candidate_count is 0.',
    learning_candidate_event_missing: 'Append learning_candidate events matching learning-capture.md candidate_count.',
    compound_review_required_for_solution_write: 'Revert the long-term solution write or add a prior matching compound_review_decision with candidate_ref, target_solution_path, decision, reason, and user_approval_event_id.',
  };
  return table[failure.id] || 'Create a proposal explaining the required safe repair.';
}

function createProposal(root, verifyResult) {
  const proposalDir = path.join(root, 'proposals', 'active');
  fs.mkdirSync(proposalDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\..+$/, 'Z');
  const proposalPath = path.join(proposalDir, `doctor-fix-${stamp}.md`);
  const lines = [
    '# Doctor Repair Proposal',
    '',
    'This proposal was generated by `harness/doctor/doctor.js --proposal`.',
    'It does not apply live repairs.',
    '',
    '## Failures',
    '',
  ];
  for (const failure of verifyResult.failures) {
    lines.push(`- ${failure.id}: ${failure.message}`);
    lines.push(`  - Suggested next action: ${nextActionFor(failure)}`);
  }
  lines.push('');
  lines.push('## Required Approval');
  lines.push('');
  lines.push('A user must approve any live file change separately. This proposal does not grant implementation, git, package, network, or harness-core write permission.');
  fs.writeFileSync(proposalPath, `${lines.join('\n')}\n`, 'utf8');
  return proposalPath;
}

function diagnose(root, options = {}) {
  const result = verifyRoot(root);
  const diagnosis = {
    ok: result.ok,
    root: result.root,
    failures: result.failures.map((failure) => ({
      ...failure,
      next_action: nextActionFor(failure),
    })),
    warnings: result.warnings,
    proposal_path: null,
  };
  if (!result.ok && options.proposal) {
    diagnosis.proposal_path = createProposal(result.root, result);
  }
  return diagnosis;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const root = path.resolve(args.root || process.cwd());
  const result = diagnose(root, { proposal: Boolean(args.proposal) });
  if (args.json) {
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  } else if (result.ok) {
    process.stdout.write(`doctor found no P0 issues for ${result.root}\n`);
  } else {
    process.stdout.write(`doctor found ${result.failures.length} issue(s) for ${result.root}\n`);
    for (const failure of result.failures) {
      process.stdout.write(`- ${failure.id}: ${failure.next_action}\n`);
    }
    if (result.proposal_path) {
      process.stdout.write(`proposal: ${result.proposal_path}\n`);
    }
  }
  process.exitCode = result.ok ? 0 : 1;
}

if (require.main === module) {
  main();
}

module.exports = {
  diagnose,
};
